php-version = "8.3.0"

[source]
paths = ["src", "tests"]
excludes = ["vendor"]

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
trailing-comma = true
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true

[linter.rules]
interface-name = { psr = false }
trait-name = { psr = false }
class-name = { psr = false }
literal-named-argument = { enabled = false }
too-many-methods = { enabled = false }
cyclomatic-complexity = { enabled = false }
tagged-todo = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-insecure-comparison = { enabled = false }
no-literal-password = { enabled = false }
kan-defect = { enabled = false }
halstead = { enabled = false }
